name: CI

on: [push]

jobs:
  run:
    name: PHP Syntax Checker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: ['7.3', '7.4', '8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Log debug information
        run: |
          git --version
          php --version
          php -i
          composer --version

      - name: Install Composer dependencies
        run: composer install

      - name: Check PHP Syntax
        run: composer run check-syntax
