name: CI

on: [push]

jobs:
  run:
    name: ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: ['7.3', '7.4', '8.0', '8.1']
        include:
          - php: '7.3'
            os: ubuntu-latest
            report: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Check PHP Version
        run: php -v

      - name: Log debug information
        run: |
          git --version
          php --version
          php -i
          composer --version

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Run (xDebug) tests
        if: ${{ matrix.report }}
        run: |
          vendor/bin/phpunit --verbose --coverage-clover=tmp/coverage/report-xml/php-coverage1.xml
          bash <(curl -s https://codecov.io/bash);